config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :neighborhoods
  get 'welcome/index'
  get 'help' => 'welcome#help'

   root 'welcome#index'

   resources :bikeroutes

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bikeroute.rb
class Bikeroute < ActiveRecord::Base
  has_and_belongs_to_many :neighborhoods
  validates :name, presence: true
  accepts_nested_attributes_for :neighborhoods
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  has_and_belongs_to_many :bikeroutes
  validates :name, presence: true
  extend FriendlyId
  friendly_id :name, :use => [:slugged, :finders]
  # existing records should run Neighborhood.find_each(&:save)
  # in console to update with slug field
  # see http://railscasts.com/episodes/314-pretty-urls-with-friendlyid
  accepts_nested_attributes_for :bikeroutes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bikeroutes_controller.rb
class BikeroutesController < ApplicationController
  if Rails.env.development?
    require 'dotenv'
  end

  def index
    @bikeroutes = Bikeroute.all
  end

  def show
    @bikeroute = Bikeroute.find(params[:id])
    @mapbox_account = ENV['MAPBOX_ACCOUNT']
    @mapbox_apikey = ENV['MAPBOX_KEY']
  end

  def new
    #@bikeroute = Bikeroute.new
  end

  def edit
    #@bikeroute = Bikeroute.find(params[:id])
  end

  def create
    # @bikeroute = Bikeroute.new(bikeroute_params)
    #
    # if @bikeroute.save
    #   redirect_to @bikeroute
    # else
    #   render 'new'
    # end
  end

  def update
    # @bikeroute = Bikeroute.find(params[:id])
    #
    # if @bikeroute.update(bikeroute_params)
    #   redirect_to @bikeroute
    # else
    #   render 'edit'
    # end
  end

  def destroy
    # @bikeroute = Bikeroute.find(params[:id])
    # @bikeroute.destroy
    #
    # redirect_to bikeroutes_path
  end

  private
  def bikeroute_params
    params.require(:bikeroute).permit(:name, :description)
  end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { render :new }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighborhood }
      else
        format.html { render :edit }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params[:neighborhood]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "CycleReady"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def is_recognised?(path)
    recognized =  Rails.application.routes.recognize_path(path)
    return recognized[:controller] == params[:controller]
  end

  def is_active?(path)
    return "active" if current_page?(path) || is_recognised?(path)
  end

end

app/helpers/bikeroutes_helper.rb
module BikeroutesHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bikeroutes/index.html.erb
<% provide(:title, "All Routes" ) %>
<script src='//d3js.org/d3.v3.min.js' charset="utf-8"></script>
<%= stylesheet_link_tag params[:controller], "data-turbolinks-track" => true %>

<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= image_tag "ic_directions_bike_black_24px.svg"%> All Bike Routes</h3>
      </div>
      <div class="panel-body">
        <div id="map-container"></div>
        <div id="route-info">
          <div id="selected-title"> <span id='selected-route'></span></div>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th><%= image_tag "ic_directions_bike_black_24px.svg"%> Name</th>
              <th>Description</th>
              <th><%= image_tag "ic_location_city_black_24px.svg"%>  Neighborhoods</th>
            </tr>
          </thead>
          <tbody>
            <% @bikeroutes.each do |bikeroute| %>
              <tr>
                <td><%= link_to bikeroute.name, bikeroute_path(bikeroute) %></td>
                <td><%= bikeroute.description[0..50] + '...' %></td>
                <td>
                  <% bikeroute.neighborhoods.each do |neighborhood| %>
                    <%= link_to neighborhood.name, neighborhood_path(neighborhood) %><%= "," unless neighborhood == bikeroute.neighborhoods.last %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'bikeroutesAll', 'data-turbolinks-track' => true %>

app/views/bikeroutes/show.html.erb
<script src='//d3js.org/d3.v3.min.js' charset="utf-8"></script>
<script src='https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.css' rel='stylesheet' />
<%= stylesheet_link_tag params[:controller], "data-turbolinks-track" => true %>
<% provide(:title, @bikeroute.name ) %>
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title"><%= image_tag "ic_directions_bike_black_24px.svg"%> <%= @bikeroute.name %></h2>
      </div>
      <div class="panel-body">

        <div class="row">
          <div class="col-md-12">
            <div id='map'></div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <p><%= @bikeroute.description %></p>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <p>About this Route:</p>
            <table class="table">
              <tbody>
                <tr>
                  <td>Lane Type:</td>
                  <td><%# @bikeroute.lane_type %>n/a</td>
                </tr>
                <tr>
                  <td>Elevation:</td>
                  <td><%# @bikeroute.grade %>--</td>
                </tr>
                <tr>
                  <td>Distance:</td>
                  <td><%= @bikeroute.distance %> miles</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <p>Elevation Profile:</p>
            <div id="elev"></div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <h5>Neighborhoods this route goes through</h5>
            <div class="list-group">
              <% @bikeroute.neighborhoods.each do |neighborhood| %>
                <%= link_to neighborhood_path(neighborhood), :class=>'list-group-item' do %>
                  <%= image_tag "ic_location_city_black_24px.svg"%>
                  <%= neighborhood.name %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <% if @bikeroute.twitter_tag.present? %>
              Have an update about this route? <br>
              <a class="twitter-hashtag-button"
                href="https://twitter.com/intent/tweet?button_hashtag=<%= @bikeroute.twitter_tag %>">
              Tweet #<%= @bikeroute.twitter_tag %></a>
            <% end %>

            <% if @bikeroute.twitter_search.present? %>
              <%= @bikeroute.twitter_search.html_safe %>
            <% end %>
          </div>
        </div>

      </div>

      <div class="panel-footer">
        <%= link_to 'Back', bikeroutes_path, :class=>"btn btn-default" %>
      </div>

    </div>
  </div>
</div>

<%= render 'layouts/twitter' %>

<script type="text/javascript">

  var routegeojson = (<%= @bikeroute.geojson.html_safe %>),
      accessToken = '<%= @mapbox_apikey %>';

  var elevationData = <%= @bikeroute.elevation.html_safe %>;

</script>
<%= javascript_include_tag params[:controller], "data-turbolinks-track" => true %>

app/views/layouts/_twitter.html.erb
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "CycleReady", root_path, id: "logo", class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <li class="<%= is_active?(root_path) %>"><%= link_to "Home", root_path %></li>
                  <li class="<%= is_active?(help_path) %>"><%= link_to "Help", help_path %></li>
                  <li class="<%= is_active?(bikeroutes_path) %>"><%= link_to "Routes", controller: 'bikeroutes' %></li>
                  <li class="<%= is_active?(neighborhoods_path) %>"><%= link_to "Neighborhoods",  controller: 'neighborhoods' %></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>


<!-- Navigation -->

app/views/neighborhoods/index.html.erb
<% provide(:title, "All Neighborhoods") %>

<script src='//d3js.org/d3.v3.min.js' charset="utf-8"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.19/topojson.min.js" charset="utf-8"></script>

<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= image_tag "ic_location_city_black_24px.svg"%> Neighborhoods:</h3>
      </div>
      <div class="panel-body">
        <div id="map-container"></div>
        <div id="neighborhood-info">
          <div id="selected-title">Neighborhood: <span id='selected-neighborhood'>San Francisco</span></div>
          <div id='selected-title-routes'></div>
        </div>
        <%= javascript_include_tag 'neighborhoodsMap', 'data-turbolinks-track' => true %>

        <div class="list-group">
          <% @neighborhoods.each do |neighborhood| %>
          <% if !!neighborhood.bikeroutes.presence %>
          <div id='<%= neighborhood.name.delete(' ').downcase %>'>
            <%= link_to neighborhood_path(neighborhood), :class=>'list-group-item' do %>
            <h4 class="list-group-item-heading"><%= image_tag "ic_location_city_black_24px.svg"%> <%=  neighborhood.name %></h4>
            <p class="list-group-item-text item-route">
              <% neighborhood.bikeroutes.each do |bikeroute| %>
              <%= bikeroute.name %><%= "," unless bikeroute == neighborhood.bikeroutes.last %>
              <% end %>
            </p>
            <% end %>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    Neighborhood Data Provided By: <a href="http://www.sfgov.org">City and County of San Francisco Planning Department</a>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/neighborhoods/show.html.erb
<% provide(:title, @neighborhood.name ) %>
<p id="notice"><%= notice %></p>
<script src='//d3js.org/d3.v3.min.js' charset="utf-8"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.19/topojson.min.js" charset="utf-8"></script>

<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= image_tag "ic_location_city_black_24px.svg"%> <%= @neighborhood.name %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <div id="map-container"></div>
            <span id='selected-route'></span>
            <script type="text/javascript">
              var neighborhoodGeojson = <%= raw @neighborhood.geojson %>,
                  routesInNeighborhoodGeojson = [
                    <% @neighborhood.bikeroutes.each do |bikeroute| %>
                      <%=raw bikeroute.geojson %><% if bikeroute != @neighborhood.bikeroutes.last %>,<% end %>
                    <% end %>
                  ];
            </script>
            <%= javascript_include_tag 'neighborhood', 'data-turbolinks-track' => true %>
          </div>
        </div>
        <hr>

        <div class="row">
          <div class="col-md-12">
            <h3>About this Neighborhood</h3>
            <%= @neighborhood.about || @neighborhood.name + ' is an awesome San Francisco neighborhood!' %>          </div>
        </div>
        <hr>

        <div class="row">
          <div class="col-md-12">
            <% if @neighborhood.bikeroutes.presence %>
              <h5>Bike Routes in this Neighborhood:</h5>
              <div class="list-group">
                <% @neighborhood.bikeroutes.each do |bikeroute| %>
                  <%= link_to bikeroute_path(bikeroute), :class=>'list-group-item' do %>
                    <h4 class="list-group-item-heading"><%= image_tag "ic_directions_bike_black_24px.svg"%> <%= bikeroute.name %></h4>
                    <p class="list-group-item-text">
                      <%= bikeroute.description[0..24] + '...' %>
                    </p>
                  <% end %>
                <% end %>
              </div>
            <% else %>
            <h5>No bike routes in the system yet</h5>
            <% end %>
          </div>
        </div>

      </div>
      <div class="panel-footer">
        <%= link_to 'Back', neighborhoods_path, :class=>"btn btn-default" %>
      </div>

    </div>
  </div>
</div>

app/views/welcome/help.html.erb
<% provide(:title, "Help" ) %>
<h1>Help</h1>
<p>
  Have a suggestion?  Want to help us out?
</p>
<p>
  Check out our <a href="https://github.com/cycleready/cycleready-web/">github account</a> and make a comment using our <a href="https://github.com/cycleready/cycleready-web/wiki/Suggest-A-Route">wiki page.</a>
</p>

app/views/welcome/index.html.erb
<% provide(:title, "Home" ) %>
<h1 class="welcome-title">SF CycleReady</h1>
 <%= image_tag "neighborhood-map.svg", :class=> "center-block img-responsive", :style=> "width:500px"%>

<div class="row">
  <div class="col-md-6 col-md-offset-3 lead">
    <p>
      CycleReady helps hesitant bikers get the hang of urban biking and enables all riders to easily access bike info, swap tips, and advocate for their favorite routes.
    </p>
    <p>
      CycleReady is a web app that offers community-powered bike navigation, helps keep riders informed, and encourages hesitant cyclists to bike in San Francisco.
    </p>
    <p>
      <a href="http://www.cycleready.com">more...</a>
    </p>

  </div>
</div>